# Generated by Django 2.1.3 on 2018-11-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fotografia',
            field=models.ImageField(upload_to='apps/adopcion/static/adpocion/img/'),
        ),
    ]
