# Generated by Django 2.1.3 on 2018-11-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0003_auto_20181110_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='fotografia',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
