# Generated by Django 2.1.3 on 2018-11-26 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0004_auto_20181113_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, null='false')),
                ('rut', models.CharField(max_length=9, null='false')),
                ('mail', models.EmailField(max_length=254, null='false')),
                ('passwd', models.CharField(max_length=40, null='false')),
                ('img_persona', models.ImageField(blank=True, default='default.jpg', upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='mascota',
            name='persona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adopcion.Persona'),
        ),
    ]
