# Generated by Django 2.1.4 on 2018-12-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0006_auto_20181130_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='mail',
            field=models.EmailField(max_length=254, null='false'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=30, null='false'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='passwd',
            field=models.CharField(max_length=40, null='false'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rut',
            field=models.CharField(max_length=9, null='false'),
        ),
    ]
