# Generated by Django 2.1.4 on 2018-12-05 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0008_auto_20181205_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='mail',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='persona',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='persona',
            name='passwd',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rut',
            field=models.CharField(max_length=9),
        ),
    ]
